### ISSUE TITLE
Explain the benefits over using the bundled FastAPI injection

### ISSUE THREAD

**Issue by mtvx** [matyasrichter/fastapi-injector#3]
What's maybe a bit lacking in the FastAPI default system are that:

- No support for injection in middlewares, exception handlers or event handlers
- No way to "manually" get a dependency
- Everything is request scoped by default (though I guess `@functools.lru_cache` can tackle that)
- Something else...

What's the selling point here, what can we achieve with this (a better way) that we cannot with the default FastAPI injector?

**Comment by matyasrichter** [comment]
Thanks for your interest!
FastAPI only provides dependency injection. Injector adds inversion of control. You can set up your bindings so that when you request an interface, you'll get its implementation injected. This allows you to loosen the coupling across your application since instead of depending directly on the concrete implementation, you only depend on an abstract "contract". 

For instance, in FastAPI, you'd typically request a DB connection (or some other class that uses it) through the dependency injection system. While that's better than creating it manually, your FastAPI endpoint is still coupled to your persistence layer. An IoC container allows you to only depend on an interface that only defines that it can "save a User". The container then injects, for example, your SQLAlchemy implementation of that interface. The outcome is that your API layer code does not control the database layer, and is relieved of that responsibility. You separate the code that sets up DB-related stuff from the code that uses it, to the point of not knowing (and thus not needing to care about) anything about your persistence layer other than "it saves a User persistently".

Some more reading:
- https://martinfowler.com/articles/injection.html
- https://livebook.manning.com/book/dependency-injection/chapter-1/18

This library is just a tiny wrapper around Alec Thomas' injector, allowing you to use it in FastAPI endpoints in a way resembling the built-in DI system.
It should be noted that IoC containers aren't always "worth the effort". FastAPI's DI system is excellent, and especially in smaller apps, the complexity added by "programming against an interface" is simply not worth it.

**Comment by mtvx** [comment]
Thanks for the quick reply and explaining that.

So, in short - you can only use `fastapi-injector` in the route functions, like the default FastAPI system. Right?

But with `fastapi-injector` you can only define the interface and the registered implementation gets auto-injected. Fair enough.

Separating interface and implementation in your standard micro-service is overkill, at least in my experience. It might be useful if you want to replace the default implementation with a test time implementation and so on, but FastAPI provides the `app.dependency_overrides` dict for that (or you could dirtily monkey patch things).

The FastAPI system is quite verbose, though, as you always need to declare the callable to retrieve the dependency from. Here that's not needed so over multiple endpoints requiring the same dependency the syntax becomes more brief, which is nice. Right?

**Comment by matyasrichter** [comment]
The idea is that you can use `fastapi-injector` in route functions, but also reuse the same `injector` setup is available for other parts of your applications, for example if you have a celery tasks, CLI interface for management commands, and so on. As in, outside of FastAPI context. Of course, not everything has a ready-to-use library for integrating `injector`, but that's often very easy to implement.

I agree with the rest of what you wrote. For a microservice, interface-impl. separation is overkill. 

The last part is exactly what I meant by separating the code that sets up dependencies from the code that uses them. Instead of always requesting the dependency through a concrete callable, you set up the provider for class `XYZ` once and then just say "this FastAPI endpoint needs dependency `XYZ`".

**Comment by mtvx** [comment]
> reuse the same `injector` setup in other parts of your application

Right, this could be nice. At the FastAPI's dependency injection only works in routes, you're left cold in other parts of your codebase.

> you set up the provider for class XYZ once and then just say "this FastAPI endpoint needs dependency XYZ".

Yeah, that's how I learn it from the Java world (those crazy `applicationContext.xml`s etc) and maybe why FastAPI approach feels a bit weird, although I cannot say that I miss the Java "good old" times :laugh:

I need to read more about `injector`. Thanks again for your responses!
